version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017
  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - server
    links:
      - server